version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1200
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 1200
      runas: ec2-user

